name: movil
description: "App Móvil - Emergencias Vehiculares"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  provider: ^6.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  web_socket_channel: ^3.0.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  record: ^7.0.0
  url_launcher: ^6.3.2
  flutter_stripe: ^11.2.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^22.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
